### ISSUE TITLE
rewind.website is down

### ISSUE THREAD

**Issue by Weldawadyathink** [joachimesque/Cast-Rewinder#11]
The website is not currently working, causing rewinded podcasts to not update. The error is 502 Bad Gateway, nginx/1.10.3 (Ubuntu).

**Comment by joachimesque** [comment]
Thank you! I restarted the server, it should be OK now.

**Comment by Weldawadyathink** [comment]
Thanks for the quick fix. I just sent a donation to keep this great service running!

**Comment by joachimesque** [comment]
Thanks a lot!

**Comment by kgraefe** [comment]
The server broke again.

**Comment by joachimesque** [comment]
> The server broke again.

Sorry about that! It's now back online.

**Comment by kgraefe** [comment]
Thank you. :-)
