### ISSUE TITLE
Can't convert Dragon Talk feed.

### ISSUE THREAD

**Issue by TKramez** [joachimesque/Cast-Rewinder#5]
I'm getting the below error when I try to convert the Dragon Talk podcast. Here is the feed url. http://www.wizards.com/dnd/rsspodcast.xml

![image](https://user-images.githubusercontent.com/2574945/46020668-e98c6400-c0ac-11e8-8bac-e111bf27e03f.png)

**Comment by joachimesque** [comment]
Hey, sorry about the late reply! It's fixed now :)

![image](https://user-images.githubusercontent.com/1781070/47448476-6a2fa480-d7c0-11e8-8436-0e75153a11cd.png)
